# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import TemperatureService_pb2 as TemperatureService__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in TemperatureService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperatureServiceStub(object):
    """Web service queried by clients to retrieve sensor data
    populated by the Kafka consumer (step 3 in the pipeline).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestReading = channel.unary_unary(
                '/temperature_service.TemperatureService/GetLatestReading',
                request_serializer=TemperatureService__pb2.SensorRequest.SerializeToString,
                response_deserializer=TemperatureService__pb2.ProcessedReading.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/temperature_service.TemperatureService/GetHistory',
                request_serializer=TemperatureService__pb2.SensorRequest.SerializeToString,
                response_deserializer=TemperatureService__pb2.ReadingHistory.FromString,
                _registered_method=True)
        self.ListSensors = channel.unary_unary(
                '/temperature_service.TemperatureService/ListSensors',
                request_serializer=TemperatureService__pb2.EmptyMessage.SerializeToString,
                response_deserializer=TemperatureService__pb2.SensorList.FromString,
                _registered_method=True)
        self.GetOverallStats = channel.unary_unary(
                '/temperature_service.TemperatureService/GetOverallStats',
                request_serializer=TemperatureService__pb2.SensorRequest.SerializeToString,
                response_deserializer=TemperatureService__pb2.OverallStats.FromString,
                _registered_method=True)


class TemperatureServiceServicer(object):
    """Web service queried by clients to retrieve sensor data
    populated by the Kafka consumer (step 3 in the pipeline).
    """

    def GetLatestReading(self, request, context):
        """Latest processed reading (avg over last 2 h) for a sensor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Full history of processed readings stored for a sensor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSensors(self, request, context):
        """IDs of all sensors seen so far
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverallStats(self, request, context):
        """Aggregated stats (global min/max/avg) across all stored readings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestReading,
                    request_deserializer=TemperatureService__pb2.SensorRequest.FromString,
                    response_serializer=TemperatureService__pb2.ProcessedReading.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=TemperatureService__pb2.SensorRequest.FromString,
                    response_serializer=TemperatureService__pb2.ReadingHistory.SerializeToString,
            ),
            'ListSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSensors,
                    request_deserializer=TemperatureService__pb2.EmptyMessage.FromString,
                    response_serializer=TemperatureService__pb2.SensorList.SerializeToString,
            ),
            'GetOverallStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverallStats,
                    request_deserializer=TemperatureService__pb2.SensorRequest.FromString,
                    response_serializer=TemperatureService__pb2.OverallStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature_service.TemperatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperature_service.TemperatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperatureService(object):
    """Web service queried by clients to retrieve sensor data
    populated by the Kafka consumer (step 3 in the pipeline).
    """

    @staticmethod
    def GetLatestReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/GetLatestReading',
            TemperatureService__pb2.SensorRequest.SerializeToString,
            TemperatureService__pb2.ProcessedReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/GetHistory',
            TemperatureService__pb2.SensorRequest.SerializeToString,
            TemperatureService__pb2.ReadingHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/ListSensors',
            TemperatureService__pb2.EmptyMessage.SerializeToString,
            TemperatureService__pb2.SensorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverallStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureService/GetOverallStats',
            TemperatureService__pb2.SensorRequest.SerializeToString,
            TemperatureService__pb2.OverallStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
