# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TemperatureService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TemperatureService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18TemperatureService.proto\x12\x13temperature_service\"\"\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyMessage\"\xae\x01\n\x10ProcessedReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08\x61vg_temp\x18\x02 \x01(\x01\x12\x10\n\x08min_temp\x18\x03 \x01(\x01\x12\x10\n\x08max_temp\x18\x04 \x01(\x01\x12\x14\n\x0csample_count\x18\x05 \x01(\x05\x12\x14\n\x0cwindow_start\x18\x06 \x01(\t\x12\x12\n\nwindow_end\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"I\n\x0eReadingHistory\x12\x37\n\x08readings\x18\x01 \x03(\x0b\x32%.temperature_service.ProcessedReading\" \n\nSensorList\x12\x12\n\nsensor_ids\x18\x01 \x03(\t\"t\n\x0cOverallStats\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x12\n\nglobal_avg\x18\x02 \x01(\x01\x12\x12\n\nglobal_min\x18\x03 \x01(\x01\x12\x12\n\nglobal_max\x18\x04 \x01(\x01\x12\x15\n\rtotal_samples\x18\x05 \x01(\x05\x32\xff\x02\n\x12TemperatureService\x12_\n\x10GetLatestReading\x12\".temperature_service.SensorRequest\x1a%.temperature_service.ProcessedReading\"\x00\x12W\n\nGetHistory\x12\".temperature_service.SensorRequest\x1a#.temperature_service.ReadingHistory\"\x00\x12S\n\x0bListSensors\x12!.temperature_service.EmptyMessage\x1a\x1f.temperature_service.SensorList\"\x00\x12Z\n\x0fGetOverallStats\x12\".temperature_service.SensorRequest\x1a!.temperature_service.OverallStats\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TemperatureService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=49
  _globals['_SENSORREQUEST']._serialized_end=83
  _globals['_EMPTYMESSAGE']._serialized_start=85
  _globals['_EMPTYMESSAGE']._serialized_end=99
  _globals['_PROCESSEDREADING']._serialized_start=102
  _globals['_PROCESSEDREADING']._serialized_end=276
  _globals['_READINGHISTORY']._serialized_start=278
  _globals['_READINGHISTORY']._serialized_end=351
  _globals['_SENSORLIST']._serialized_start=353
  _globals['_SENSORLIST']._serialized_end=385
  _globals['_OVERALLSTATS']._serialized_start=387
  _globals['_OVERALLSTATS']._serialized_end=503
  _globals['_TEMPERATURESERVICE']._serialized_start=506
  _globals['_TEMPERATURESERVICE']._serialized_end=889
# @@protoc_insertion_point(module_scope)
